# Generated by Django 3.1.4 on 2021-01-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='allergy',
            new_name='allergies',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='feel',
            new_name='feels',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='sub_cateogry',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='taste',
            new_name='tastes',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(),
        ),
    ]
