# Generated by Django 3.1.4 on 2021-01-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='description',
            new_name='main_description',
        ),
        migrations.RemoveField(
            model_name='size',
            name='cup_size',
        ),
        migrations.RemoveField(
            model_name='size',
            name='ounce_size',
        ),
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='sub_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.drink'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='caffeine',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='kcal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='saturation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sodium',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
