# Generated by Django 3.1.4 on 2021-01-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210127_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='is_new',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='is_season',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
