# Generated by Django 3.1.5 on 2021-02-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_drink_propensity'),
        ('product', '0002_auto_20210129_0629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taste',
            new_name='DrinkStatus',
        ),
        migrations.RemoveField(
            model_name='drinktaste',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='drinktaste',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='image',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='feels',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='tastes',
        ),
        migrations.AddField(
            model_name='drink',
            name='drink_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='product.drinkstatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='feel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drink',
            name='image_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='taste',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drink',
            name='destiny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='drinkstatus',
            table='drinkstatuses',
        ),
        migrations.DeleteModel(
            name='DrinkFeel',
        ),
        migrations.DeleteModel(
            name='DrinkTaste',
        ),
        migrations.DeleteModel(
            name='Feel',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
