# Generated by Django 3.1.4 on 2021-01-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='userdrinkstatus',
            table='userdrinkstatuses',
        ),
    ]
