# Generated by Django 3.1.5 on 2021-01-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210129_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='drink_propensity',
            field=models.JSONField(null=True),
        ),
    ]
