# Generated by Django 3.1.5 on 2021-02-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210129_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='drink_propensity',
        ),
    ]
