# Generated by Django 3.1.5 on 2021-02-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210201_1230'),
        ('user', '0004_remove_user_drink_propensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='destiny',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='drink_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.drinkstatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='feel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='taste',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserDrinkStatus',
        ),
    ]
