# Generated by Django 3.1.4 on 2021-01-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='orderstatuses',
        ),
    ]
