# Generated by Django 3.1.4 on 2021-01-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.BooleanField(),
        ),
    ]
